### ISSUE TITLE
和PetDragon插件冲突

### ISSUE THREAD

**Issue by TiaTheFairy** [iXanadu13/EnderDragon#14]
PetDragon : https://www.spigotmc.org/resources/petdragon-lite-ridable-enderdragons-1-14-1-20-4-support.82744/
使用PetDragon插件生成一条宠物末影龙时，EnderDragon插件会将宠物龙也计入EnderDragon的龙，并给他赋一个setting里面的类型。
然后使用PetDragon的命令删除宠物龙后，再召唤宠物龙，EnderDragon仍会播报第xx条龙一出生，但播报末影龙类型的那一条消息变成了空白，且龙的编号条数和上次的一样。
![1](https://github.com/iXanadu13/EnderDragon/assets/69950541/ce60c843-0078-4915-a1a8-68b13d80b35a)
![2](https://github.com/iXanadu13/EnderDragon/assets/69950541/8b8669fc-d689-4215-92cf-496edd6cb7eb)

**Comment by iXanadu13** [comment]
修改config.yml中的选项：
```yaml
blacklist_spawn_reason: [CUSTOM]
```

**Comment by iXanadu13** [comment]
2.5.0版本已兼容PetDragon，感谢你的反馈~
