### ISSUE TITLE
 [Request] Add an option to disable online updates

### ISSUE THREAD

**Issue by 1343008086** [iXanadu13/EnderDragon#17]
The online update check is very annoying, sometimes garbage logs appear when the network is poor, I hope to add an option in the config to disable the update check.

**Comment by iXanadu13** [comment]
The update checking remind will only be sent once when the sever is loaded/reloaded, and it can remind user to use the latest version.
And I have add try/catch block in new versions, so no log will appear even if your network is poor.

**Comment by iXanadu13** [comment]
EnderDragon v2.5.2 has been released.
You can add
```yaml
skip_update_check: true
```
in config.yml to skip the update checking.
