### ISSUE TITLE
Well i want to ask something

### ISSUE THREAD

**Issue by AdwinL** [iXanadu13/EnderDragon#22]
I don't know why my loot is not being distributed and the dragon report have nothing in it

![2024-05-20_00 49 59](https://github.com/iXanadu13/EnderDragon/assets/47217803/3255eae4-94ba-4879-8b52-79e123f15394)

**Comment by AdwinL** [comment]
https://imgur.com/undefined

**Comment by iXanadu13** [comment]
Please provide server type, version, plugin version and more useful information.

**Comment by iXanadu13** [comment]
It seems that the plugin works fine.
<details>

![image](https://github.com/iXanadu13/EnderDragon/assets/104714710/e8ee501b-0250-4d10-8b9b-0d5270fd667b)
</details>

**Comment by AdwinL** [comment]
sorry i'm currently using spigot 1.20.4 the plugin version 2.5.2. maybe i'm having issue with the script can you look at the code
[EnderDragon.zip](https://github.com/iXanadu13/EnderDragon/files/15376233/EnderDragon.zip)

**Comment by iXanadu13** [comment]
<details>

![image](https://github.com/iXanadu13/EnderDragon/assets/104714710/6d09ab46-7dc8-405f-94bf-6e6bc7021086)
</details>

I used your config and tested in spigot-1.20.4 server, but everything works fine.
