### ISSUE TITLE
Dragon respawn timer

### ISSUE THREAD

**Issue by Phillip0810** [iXanadu13/EnderDragon#3]
Can a dragon respawn timer be added ingame.

Simply a command users will use to see when the next dragon is due to respawn

**Comment by iXanadu13** [comment]
I plan to add another respawn method which bases on countdown.
In that mode, you can simply use /ed respawn_cd get <world_name> or PAPI to get the precise remain time.
I will release it before the end of July.

**Comment by iXanadu13** [comment]
Install the new version: 2.1.0

**Comment by iXanadu13** [comment]
Install the new version: 2.1.0
