### ISSUE TITLE
Enderdragon max health

### ISSUE THREAD

**Issue by Averroesmc** [iXanadu13/EnderDragon#5]
When I set max_health: to more than 2048, ender dragon spawns with 2048 HP

**Comment by iXanadu13** [comment]
It is a default restriction of the server instead of this plugin.
You can revise it at settings.attribute.maxHealth.max of spigot.yml.

![image](https://github.com/iXanadu13/EnderDragon/assets/104714710/9bbf271c-dd34-4f88-b060-027719108fca)

**Comment by Averroesmc** [comment]
Oh, that makes sense, sorry for bothering
